language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
services:
  - docker
before_install:
  - chmod +x mvnw
  - docker-compose -f src/main/docker/postgresql.yml up -d

deploy:
  provider: heroku
  api_key: 164b3b4f-06ef-4d70-af74-78f0d5b52f45
  app: cashback-beblue
