language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
env:
  - DOCKER_COMPOSE_VERSION=1.4.2
services:
  - docker
before_install:
  - chmod +x mvnw
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -f src/main/docker/postgresql.yml up -d

deploy:
  provider: heroku
  api_key: 164b3b4f-06ef-4d70-af74-78f0d5b52f45
  app: cashback-beblue
